[toolchain]
channel = "1.84.0"
components = ["rustfmt", "clippy", "rust-src"]
targets = [
    "aarch64-linux-android",
    "armv7-linux-androideabi",
    "x86_64-linux-android",
    "i686-linux-android",
    "x86_64-unknown-linux-gnu",
]
