[package]
name = "gravital-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[lib]
path = "src/lib.rs"

[[bin]]
name = "fuzz_proto_parse"
path = "fuzz_targets/fuzz_proto_parse.rs"
test = false
doc = false

[[bin]]
name = "fuzz_socks_proto"
path = "fuzz_targets/fuzz_socks_proto.rs"
test = false
doc = false

[[bin]]
name = "fuzz_stack_inbound"
path = "fuzz_targets/fuzz_stack_inbound.rs"
test = false
doc = false

[dependencies]
libfuzzer-sys = "0.4"
gravital-proto = { path = "../crates/gravital-proto" }
gravital-stack = { path = "../crates/gravital-stack" }
bytes = "1"

[profile.release]
opt-level = 3
debug = false
