[package]
name = "gravital-http"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
tokio = { workspace = true }
bytes = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
httparse = { workspace = true }
gravital-obs = { path = "../gravital-obs" }
