[package]
name = "gravital-stack"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
smoltcp = { workspace = true }
tokio = { workspace = true }
bytes = { workspace = true }
parking_lot = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
gravital-obs = { path = "../gravital-obs" }
