[package]
name = "gravital-engine"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "gravital_engine"
crate-type = ["staticlib", "cdylib", "rlib"]

[dependencies]
tokio = { workspace = true }
bytes = { workspace = true }
parking_lot = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
once_cell = { workspace = true }

gravital-proto  = { path = "../gravital-proto" }
gravital-obs    = { path = "../gravital-obs" }
gravital-tun    = { path = "../gravital-tun" }
gravital-socks  = { path = "../gravital-socks" }
gravital-http   = { path = "../gravital-http" }
gravital-stack  = { path = "../gravital-stack" }
gravital-dns    = { path = "../gravital-dns" }
gravital-udpgw  = { path = "../gravital-udpgw" }
gravital-ffi    = { path = "../gravital-ffi" }

[dev-dependencies]
tokio = { workspace = true, features = ["test-util"] }
